### ISSUE TITLE
Can the name be changed?

### ISSUE THREAD

**Issue by impressivewebs** [abhishekbhardwaj/chakraui-react-next.js-typescript-eslint-jest-starter#1]
I'd love to feature this in my newsletter, [Web Tools Weekly](https://webtoolsweekly.com/), but the title is really long! Can you shorten it to something more memorable?

Here are some suggestions:

* chakra-react-starter
* chakra-kitchen-sink-starter
* chakra-next-template

"Kitchen Sink" is a common way in English to refer to "everything".  😄

**Comment by abhishekbhardwaj** [comment]
@impressivewebs  Hey sorry for the late response to this. I was away for the last month due to COVID.
I'm sort of trying to keep it uniform with my other boilerplate.
